language: rust
dist: bionic

rust:
  - 1.40.0
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly

cache: cargo

install:
  - if [ $TRAVIS_RUST_VERSION = "stable" ]; then rustup component add rustfmt; fi

script:
  - if [ $TRAVIS_RUST_VERSION = "stable" ]; then cargo fmt --all -- --check; fi
  - cargo build --verbose
  - cargo test --verbose

deploy:
  provider: cargo
  token:
    secure: "Q/2iAydnZe6LRZBqcuQvDarni34zj9bFHc/gIgfQhGJLk5IYhk3+Bhte+8OwUwsn3PHV7FFi+vKveRxiZzhG3pJiLAj1HP2Tz8m+mxdpQx90mkTxlVoI3O6U6AuSgFrMA9eSZ1zDmtQuIwpDI5nPaYCLzqZ1akeK/jGi9HResMD5Qx7lKFvPGJWKJd7rvhT+Jbr1MHcwYn9FN0ucKsTFW7/jVfp+twZZJpqEktbTG5uZq5K7zor2m6qarm6km8w4+O7p0vCbFRPbhlSXqPcHgMqlZEHMyIwMwV2UeWFPGlvsgQ/0CzDtyCRkEyFb76FA12L77gbd5KwJhLKYEBkL45/z3FyMnguEcF8N8IF4gUYb8nZqEfnzd4oh4aagQqJuCPZ5eu5wkH8JD2oo5ISJzQsbZU1iiULq7vOZnjcM/5LzZhozO7nN9EdmMWmaopRvJQlDM8GVz9dQjpCF8wVDqmkziv4tKlCQ488jXTYA4PLe2vKNcHByqIzmDtxXXce9/38l4a0X4EtWcd2z8Hxg3RwiExGW737FHMfnYE382tnhgkryhTSBK9W3PP/9la0fXELRqa11jJOpeJshoKoUSMUS4ud0cAnmfwy/bX60XHWAbF9Yqh/b+boifQYn2BCRTAw2x3lTX5CVRlod+CWGDjjgvFdUT6UmOA8WSNhPWvs="
  on:
    tags: true
    rust: stable
