language: rust
dist: bionic

rust:
  - 1.40.0
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly

cache: cargo

install:
  - if [ $TRAVIS_RUST_VERSION = "stable" ]; then rustup component add rustfmt; fi

script:
  - if [ $TRAVIS_RUST_VERSION = "stable" ]; then cargo fmt --all -- --check; fi
  - cargo build --verbose
  - cargo test --verbose

deploy:
  provider: cargo
  token:
    secure: "BPwIgi/n4sYREpUfwukMOKfZ9YepoNwGodmC6hjitlaJUAt4+RBQ98MUP7EkJZiLdf20saHM6JUwz9m/rTjpmoX/0QG2z6BILexIeKL5ixvYRaBgW2+lXvms7xb1u2zqMRwXzXy24Zfbi0bgQAx7Boeqiu3L6ZlQ8l9AQFNLh4ED7/SpMOxU4NMOJ9TOfdSyRzxyJJx9NJniuIlitjvQNA7639TuFYdnvqVle8wI9M5iIKAEGAu8KYVHgi1iEH/VUvjDIfYxPTODVVFgBCmR1mHEQF1hMgBTW2S6UykfvhRwuridZAn9sixCjupMXym49E17n62WjBWxj9TunDopXdYtXIABHG3CXKfJSz/skxvAME9hJy2BXmTBg+m5g0KfoZUKTMfrymd1vgOmtXCOc+p2xdGlkmRLrk9Cu11nOjiwwjHuD1HKCG+fve3YcrHYywgEoKzVg0H4po/ldrdxfI3YJQBANkvuavOl0xStPCyP0hWz3NJ/0pCxyAQZgK2SPJpp88/9Om3sljMDShf84N4B6CXAS8IA9XJ3MUTl38Pb20K9CFpgJ/XfvFfIQQro6rttBsA5uPNfSRat6Vh3PYUwaUVZngS6sBgKl9KuPzm323/ArNBR762p/3WiTUCHkc+0MyxmBryODRfS0qBRnQHbm5Xly5gJ0juW08PrNQw="
  on:
    tags: true
    rust: stable
