language: rust
dist: bionic

rust:
  - 1.40.0
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly

cache: cargo

install:
  - if [ $TRAVIS_RUST_VERSION = "stable" ]; then rustup component add rustfmt; fi

script:
  - if [ $TRAVIS_RUST_VERSION = "stable" ]; then cargo fmt --all -- --check; fi
  - cargo build --verbose
  - cargo test --verbose
