[package]
name = "mdbook-curly"
version = "0.1.0"
authors = ["Armin Häberling <armin.aha@gmail.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
mdbook = { version = "0.3.7", default-features = false }
pulldown-cmark = "0.6.1"
pulldown-cmark-to-cmark = "2.0.1"
semver = "0.9.0"
serde_json = "1.0.52"
structopt = "0.3.14"
