[package]
name = "mdbook-curly"
version = "0.1.0"
authors = ["Armin Häberling <armin.aha@gmail.com>"]
edition = "2018"

[dependencies]
mdbook = "0.3.7"
semver = "0.9.0"
serde_json = "1.0.52"
structopt = "0.3.14"
